// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


var windowExists = ( typeof window !== 'undefined' );

console.log(window.navigator.userAgent);

var partial_arg = window.navigator.userAgent;

function checkIndexOf(param) {
  return param.indexOf(partial_arg);
}

exports.windowExists = windowExists;
exports.checkIndexOf = checkIndexOf;
/* windowExists Not a pure module */
