// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


var windowExists = ( typeof window !== 'undefined' );

console.log(window.navigator.userAgent.indexOf("Firefox"));

function agent(key) {
  return window.navigator.userAgent.indexOf(key);
}

exports.windowExists = windowExists;
exports.agent        = agent;
/* windowExists Not a pure module */
